import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * RootLayout component.
 * @param {Object} props - The component props.
 * @param {JSX.Element} props.children - The child elements.
 * @returns {JSX.Element} The root layout component.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
